apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  REDIS_ADDR: {{ .Values.config.redisAddr | quote }}
  POSTGRES_DSN: {{ .Values.config.postgresDsn | quote }}
  ROUTING_SERVICE_URL: {{ .Values.config.routingServiceUrl | quote }}
