{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-services
  labels:
    {{- include "metroride.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      metroride.io/metrics: "true"
  endpoints:
    - port: http
      path: /metrics
{{- end }}
